modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="simpledelights" #mandatory
version="${file.jarVersion}"
displayName="Simple Delights"
logoFile="simpledelights.png"
authors="CorgiBlu"
credits="Anna Erisian"
description='''
Adds some new foods using both Simple Farming and Farmer's Delight
'''
[[dependencies.simpledelights]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simpledelights]]
    modId="minecraft"
    mandatory=true
versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simpledelights]]
    modId="simplefarming"
    mandatory=true
    versionRange="[1.19.2-2.0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simpledelights]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="NONE"
    side="BOTH"
